name: marp-to-pages
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Marp Build (README)
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: README.md -o README-HTML.html
        env:
          MARP_USER: root:root
      - uses: stefanzweifel/git-auto-commit-action@v4
